use_frameworks!

target 'CGSimplePing_Example' do
  pod 'CGSimplePing', :path => '../'

  target 'CGSimplePing_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
